import React, { useState, useEffect } from 'react';
import { db } from '../services/db';
import { Appointment, Doctor, Clinic, AppointmentStatus } from '../types';
import { useLanguage } from '../App';

export const Appointments: React.FC = () => {
  const { t } = useLanguage();
  const [appointments, setAppointments] = useState<Appointment[]>([]);
  const [doctors, setDoctors] = useState<Doctor[]>([]);
  const [view, setView] = useState<'list' | 'new'>('list');
  
  // Form State
  const [selectedDoctor, setSelectedDoctor] = useState('');
  const [selectedDate, setSelectedDate] = useState('');
  const [selectedTime, setSelectedTime] = useState('');
  const [patientName, setPatientName] = useState('');
  const [patientPhone, setPatientPhone] = useState('');

  const loadData = async () => {
    const [apts, docs] = await Promise.all([
        db.appointments.getAll(),
        db.doctors.getAll()
    ]);
    setAppointments(apts);
    setDoctors(docs);
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleBook = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedDoctor || !selectedDate || !selectedTime) return;

    // Find clinic from schedule
    const allSchedules = await db.schedules.getAll();
    const docSchedule = allSchedules.filter(s => s.doctor_id === selectedDoctor);
    // Simplified: Default to first clinic found or random ID if none
    const clinicId = docSchedule.length > 0 ? docSchedule[0].clinic_id : (await db.clinics.getAll())[0]?.id;

    const newAppt: Appointment = {
      id: '', // Generated by DB
      doctor_id: selectedDoctor,
      clinic_id: clinicId,
      date: selectedDate,
      time: selectedTime,
      patient_name: patientName,
      patient_phone: patientPhone,
      status: AppointmentStatus.PENDING
    };

    await db.appointments.create(newAppt);
    await loadData();
    setView('list');
    
    // Reset form
    setPatientName(''); setPatientPhone(''); setSelectedDate(''); setSelectedTime('');
  };

  const updateStatus = async (id: string, status: AppointmentStatus) => {
      const appt = appointments.find(a => a.id === id);
      if(appt) {
          await db.appointments.update({ ...appt, status });
          await loadData();
      }
  }

  // Generate simple slots (Mock logic)
  const generateSlots = () => {
      return ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '13:00', '13:30', '14:00'];
  };

  return (
    <div className="space-y-6 font-sans">
      <div className="flex justify-between items-center">
        <h2 className="text-3xl font-bold text-gray-800">{t.appointments}</h2>
        <button 
            onClick={() => setView(view === 'list' ? 'new' : 'list')}
            className="bg-primary hover:bg-blue-700 text-white px-4 py-2 rounded shadow transition"
        >
            {view === 'list' ? `+ ${t.bookNew}` : t.cancelBooking}
        </button>
      </div>

      {view === 'new' && (
        <div className="bg-white p-6 rounded-xl shadow-md animate-fade-in-down">
            <h3 className="text-xl font-semibold mb-4 text-gray-700">{t.bookNew}</h3>
            <form onSubmit={handleBook} className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">{t.selectDoctor}</label>
                    <select 
                        className="w-full border p-2 rounded focus:ring-2 focus:ring-primary outline-none"
                        value={selectedDoctor}
                        onChange={(e) => setSelectedDoctor(e.target.value)}
                        required
                    >
                        <option value="">{t.chooseDoctor}</option>
                        {doctors.map(d => (
                            <option key={d.id} value={d.id}>{d.name}</option>
                        ))}
                    </select>
                </div>
                <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">{t.date}</label>
                    <input 
                        type="date" 
                        className="w-full border p-2 rounded focus:ring-2 focus:ring-primary outline-none"
                        value={selectedDate}
                        onChange={(e) => setSelectedDate(e.target.value)}
                        required
                    />
                </div>
                 <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">{t.timeSlot}</label>
                    <select 
                        className="w-full border p-2 rounded focus:ring-2 focus:ring-primary outline-none"
                        value={selectedTime}
                        onChange={(e) => setSelectedTime(e.target.value)}
                        required
                        disabled={!selectedDate}
                    >
                        <option value="">{t.chooseTime}</option>
                        {generateSlots().map(t => <option key={t} value={t}>{t}</option>)}
                    </select>
                </div>
                 <div className="col-span-1 md:col-span-2 grid grid-cols-2 gap-6">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">{t.patientName}</label>
                        <input 
                            type="text" 
                            className="w-full border p-2 rounded focus:ring-2 focus:ring-primary outline-none"
                            value={patientName}
                            onChange={(e) => setPatientName(e.target.value)}
                            required
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">{t.phone}</label>
                        <input 
                            type="tel" 
                            className="w-full border p-2 rounded focus:ring-2 focus:ring-primary outline-none"
                            value={patientPhone}
                            onChange={(e) => setPatientPhone(e.target.value)}
                            required
                        />
                    </div>
                </div>
                <div className="col-span-1 md:col-span-2">
                    <button type="submit" className="w-full bg-primary text-white py-3 rounded font-bold hover:bg-blue-700 transition">{t.confirmBooking}</button>
                </div>
            </form>
        </div>
      )}

      {/* Appointment List */}
      <div className="bg-white rounded-xl shadow-sm overflow-hidden">
        <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
                <tr>
                    <th className="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase tracking-wider">{t.patientName}</th>
                    <th className="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase tracking-wider">{t.doctors}</th>
                    <th className="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase tracking-wider">{t.date}</th>
                    <th className="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase tracking-wider">{t.status}</th>
                    <th className="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase tracking-wider">{t.actions}</th>
                </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
                {appointments.map(apt => {
                    const docName = doctors.find(d => d.id === apt.doctor_id)?.name || 'Unknown';
                    return (
                        <tr key={apt.id}>
                            <td className="px-6 py-4 whitespace-nowrap">
                                <div className="text-sm font-medium text-gray-900">{apt.patient_name}</div>
                                <div className="text-sm text-gray-500">{apt.patient_phone}</div>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{docName}</td>
                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                {apt.date} <span className="font-bold ms-2">{apt.time}</span>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap">
                                <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full 
                                    ${apt.status === 'CONFIRMED' ? 'bg-green-100 text-green-800' : 
                                      apt.status === 'PENDING' ? 'bg-yellow-100 text-yellow-800' : 
                                      apt.status === 'CANCELLED' ? 'bg-red-100 text-red-800' : 'bg-gray-100 text-gray-800'}`}>
                                    {apt.status}
                                </span>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap text-sm font-medium space-x-2 gap-2 flex">
                                <button onClick={() => updateStatus(apt.id, AppointmentStatus.CONFIRMED)} className="text-green-600 hover:text-green-900">{t.confirm}</button>
                                <button onClick={() => updateStatus(apt.id, AppointmentStatus.CANCELLED)} className="text-red-600 hover:text-red-900">{t.cancel}</button>
                            </td>
                        </tr>
                    )
                })}
            </tbody>
        </table>
        {appointments.length === 0 && <div className="p-8 text-center text-gray-500">{t.noAppointments}</div>}
      </div>
    </div>
  );
};